### ISSUE TITLE
complex description logic queries giving error 500

### ISSUE THREAD

**Issue by reality** [bio-ontology-research-group/aberowlweb#100]
examples: 

http://www.aber-owl.net/api/dlquery?labels=true&query=%27part%20of%27%20some%20%27apoptotic%20process%27&type=subeq&offset=1

http://www.aber-owl.net/api/dlquery?labels=true&query=%27has%20part%27%20%20some%20(%27increased%20pressure%27%20and%20(%27inheres%20in%27%20some%20(blood)))&type=subeq&offset=1

weirdly, simple queries of a single concept are working: http://www.aber-owl.net/api/dlquery?labels=true&query=hypertension&type=subeq

**Comment by reality** [comment]
i would recommend that this issue is given a high priority, as i will submit a paper today that depends on this functionality

**Comment by aliraza995** [comment]
Aaha. I am working on it this one is very strange error since the same DL queries are perfectly fine local machine but on production it somehow breaking. I am trying to debug it. Thanks for the patience.

**Comment by aliraza995** [comment]
Fixed. Thanks for reporting it.

**Comment by reality** [comment]
Awesome! Thank you for fixing it so quickly
