### ISSUE TITLE
API routes with / at the end aren't found

### ISSUE THREAD

**Issue by reality** [bio-ontology-research-group/aberowlweb#103]
it's a pretty small issue, but can be confusing, e.g. 

http://www.aber-owl.net/api/dlquery/?labels=true&query=%27has%20part%27%20%20some%20(%27increased%20pressure%27%20and%20(%27inheres%20in%27%20some%20(blood)))&type=subeq&offset=1&ontology=HP

then removing the / to make it 

http://www.aber-owl.net/api/dlquery?labels=true&query=%27has%20part%27%20%20some%20(%27increased%20pressure%27%20and%20(%27inheres%20in%27%20some%20(blood)))&type=subeq&offset=1&ontology=HP

makes it work

**Comment by aliraza995** [comment]
We have removed the additional slash from Url after "/api/dlquery" to make it unambiguous and consistent with url pattern in the API documentation. I understand all the refactoring is bit confusing if one is already using the API these changes might be annonying. We are thinking about coming up with a machanism of giving changes in the form of releases and somehow communicate the release notes to user too. However it still needs to be discussed. Thanks
