### ISSUE TITLE
problem with API slashes

### ISSUE THREAD

**Issue by reality** [bio-ontology-research-group/aberowlweb#104]
I've finally figured out what was bothering me about the API routes! I think there's a faulty rewrite rule (although it could be a problem of my browser, lets see if you can reproduce it). Steps to repeat:

1. browse to http://www.aber-owl.net/api/dlquery/?type=subeq&labels=true&query=hypertension&offset=1
2. Correctly, resource not found
3. Browse to http://www.aber-owl.net/api/dlquery?type=subeq&labels=true&query=hypertension&offset=1
4. Note that the URL is rewritten to that in step 1, and is not found

This only happens when 'www' is in the URL, so I guess it's a problem of the reverse proxy automatically adding a / on the end when that is the case?

**Comment by aliraza995** [comment]
It seems to be working alright on chrome and IE. Its not appending a extra / after dlquery.

**Comment by aliraza995** [comment]
I will try to reproduce it again. Because I encountered something like this earlier and will get back to you soon.

**Comment by reality** [comment]
I tried it on another machine, and could not reproduce it. I guess it's a cache issue then? Maybe you're having the problem now because of having browsed to / from step 1?

I wonder if there be any consistency problem with automatically redirecting the / form to the non-/ form?

**Comment by aliraza995** [comment]
Actually the slashes after the resource name (like dlquery here) have been removed while the aberowl API was refactored. It was done in order to make API urls REST like. In the updated API documentation, you can see that there is no slash at the end of url and before query string.

http://aber-owl.net/docs/
