### ISSUE TITLE
Documentation for API

### ISSUE THREAD

**Issue by leechuck** [bio-ontology-research-group/aberowlweb#35]
The AberOWL API needs to be documented and examples created, and there should be a link to the API on the main page.

**Comment by leechuck** [comment]
Using the smartAPI standard, if possible.

**Comment by aliraza995** [comment]
I have added and initial possible documentation of aberow current API and it is available on http://aber-owl.net/docs/. To make it complete smartAPI we may need to rewrite the APIs and might require radical changes on both backend and front end. API written right now are more of functions available on http with no specification of internal models, to give it restful resource view is would help to achieve smart API standard. Let me know about your comments or suggestions:

**Comment by leechuck** [comment]
http://aber-owl.net/docs/ gives a 500 -- Server error at the moment.

**Comment by aliraza995** [comment]
@leechuck Noted. Thanks

**Comment by aliraza995** [comment]
Update API documentation is available on http://aber-owl.net/docs/
