### ISSUE TITLE
Weights and indexing in ElasticSearch

### ISSUE THREAD

**Issue by leechuck** [bio-ontology-research-group/aberowlweb#37]
The weights of the matches in different fields need to be updated.
Currently, searching by OBO ID gives no results. IDs should be higher than Labels should be higher than Synonyms should be higher than Definition should be higher than rest. This needs to be implemented in ElasticSearch indexes.

**Comment by leechuck** [comment]
And the "Ontology" field needs to be searchable, too; if I search "apoptosis GO" I want the GO apoptosis class as the first hit.

**Comment by aliraza995** [comment]
@leechuck I have updated the electic search query but we will need to update mappings on elasticsearch server too for indices to get the desired search results. Currently indices have default mappings.  I have asked Zulfikar to update the mappings.
