### ISSUE TITLE
Flat hierarchy in tree view returns everything in ontology under root node

### ISSUE THREAD

**Issue by reality** [bio-ontology-research-group/aberowlweb#73]
Steps to repeat:

1. Browse to http://www.aber-owl.net/ontology/ENM/
2. Expand 'entity' in the left tree
3. wait a long time
4. Every class in the ontology will open under entity

If you click on one, changing the current window url to http://www.aber-owl.net/ontology/ENM/#/Browse/%3Chttp%3A%2F%2Fsemanticscience.org%2Fresource%2FCHEMINF_000049%3E then reload the page, the hierarchy will load correctly.

My guess would be that direct=false, for some reason, but the tools show that the query run is: 
http://www.aber-owl.net/api/dlquery/?type=subclass&direct=true&axioms=true&query=%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FBFO_0000001%3E&ontology=ENM

Could this parameter be failing for some reason? I suppose the reason it works upon reload is getPathToRoot doesn't subclass query entity. Could there be some eccentricity of the ontology itself causing everything to be a direct subclass of entity?

**Comment by reality** [comment]
seems to also be the case for other ontologies e.g. http://aber-owl.net/ontology/IAO/

**Comment by leechuck** [comment]
I can confirm this bug. Looks like https://github.com/bio-ontology-research-group/aberowlweb/blob/402e34c61652107d25fba59ed7893ef7e744c06f/aberowlweb/apps/aberowl/api_views.py#L589 is missing the parameter for "direct".

**Comment by leechuck** [comment]
And https://github.com/bio-ontology-research-group/aberowlweb/blob/f939ddee962243e84b7a4a9e7b00ce2b4cf150c7/aberowlweb/apps/aberowl/ont_server_request_processor.py#L37 needs to handle the direct parameter as well.

**Comment by coolmaksat** [comment]
Fixed
