### ISSUE TITLE
querynames API confusion

### ISSUE THREAD

**Issue by reality** [bio-ontology-research-group/aberowlweb#75]
querynames seems to have been partially replaced by searchclasses. now, querynames doesn't return any results if given an "ontology" parameter. since they both have the same type of result, could these endpoints be consolidated? if not, perhaps an error message could be added to the querynames endpoint, if calling it with an ontology parameter, that guides you to the searchclasses endpoint.

**Comment by aliraza995** [comment]
@reality querynames doesnt giving any results if given an "ontology" param was bug so I fixed it. The two APIs are for different purposes searchclasses is for autocomplete labels within an ontology for typeahead input boxes and other for general search over all classes and their elements. Therefore combining may create more confusion.
However we have refactored the Aberowl API to be more REST like APIs. The two APIs are now:

- /api/ontology/_find (querynames)

- /api/ontology/_startwith (searchclasses)

Here is the updated  API documentation: 
http://aber-owl.net/docs/
