### ISSUE TITLE
Which annotation properties are indexed into _.find synonyms?

### ISSUE THREAD

**Issue by reality** [bio-ontology-research-group/aberowlweb#88]
I see that the querynames API has changed to _find. Could I pelase have a list of annotation properties that are included in the 'synonyms' key for that model? Maybe it would be good to put this in the documentation, also

**Comment by aliraza995** [comment]
Hi Luke,
Here is the list of annontation properties that are included in synonyms:
http://www.w3.org/2004/02/skos/core#altLabel
http://purl.obolibrary.org/obo/IAO_0000118
http://www.geneontology.org/formats/oboInOwl#hasExactSynonym
http://www.geneontology.org/formats/oboInOwl#hasSynonym
http://www.geneontology.org/formats/oboInOwl#hasNarrowSynonym
http://www.geneontology.org/formats/oboInOwl#hasBroadSynonym

I have also added this information and the information about other properties that  include mapping from annotation properties such as identifiers, labels and definitions to API documentation as well. Thanks
