### ISSUE TITLE
cannot browse phenomenet from website

### ISSUE THREAD

**Issue by reality** [bio-ontology-research-group/aberowlweb#92]
the tree view does not load, see: http://www.aber-owl.net/ontology/PhenomeNET/

It looks like there's some kind of error: from the API: http://www.aber-owl.net/api/dlquery/?type=subeq&labels=true&query=hypertension&ontology=PhenomeNET

**Comment by aliraza995** [comment]
Thanks for reporting the issue. It is fixed now
